---
abstract: 'I2C interface to L3GD20 3 axis GyroScope using Device::SMBus'
author:
  - 'Shantanu Bhadoria <shantanu at cpan dott org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::Util: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Device-L3GD20
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
    - inc
  package:
    - DB
provides:
  Device::Gyroscope::L3GD20:
    file: lib/Device/Gyroscope/L3GD20.pm
    version: 0.005
  Device::L3GD20:
    file: lib/Device/L3GD20.pm
    version: 0.005
requires:
  Device::SMBus: 0
  Moose: 0
  POSIX: 0
  Time::HiRes: 0
  constant: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/shantanubhadoria/device-l3gd20/issues
  homepage: https://metacpan.org/release/Device-L3GD20
  repository: git://github.com/shantanubhadoria/device-l3gd20.git
version: 0.005
x_contributors:
  - 'Shantanu <shantanu@cpan.org>'
  - 'Shantanu Bhadoria <shantanu@cpan.org>'
